---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: '14.04'

inputs:
  - name: australia-repo

run:
  path: ./run-tests.sh
  dir: src/extensions/australia/
