---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: '14.04'

inputs:
  - name: sweden-repo

run:
  path: ./run-tests.sh
  dir: sweden-repo/src/extensions/sweden/
