---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: '14.04'

inputs:
  - name: theme--base-repo

run:
  path: ./run-tests.sh
  dir: theme-base-repo/src/extensions/theme--base/
